### ISSUE TITLE
Access from Java

### ISSUE THREAD

**Issue by cristarra** [1AboveAll/Hasher#1]
The best way to access Kotlin Companion object from java like this

`Hasher.Companion.hash(value,HashType);`

maybe, will not be found if it is like this

```
//Call hash() method using the object
Hasher.hash(value,HashType);
```

reference https://stackoverflow.com/questions/38120494/how-to-access-kotlin-companion-object-in-java

**Comment by ihimanshurawat** [comment]
Thank you so much for addressing this issue. I have updated the read me.
